// Generated by gencpp from file husky_highlevel_controller/AddTwoInts.msg
// DO NOT EDIT!


#ifndef HUSKY_HIGHLEVEL_CONTROLLER_MESSAGE_ADDTWOINTS_H
#define HUSKY_HIGHLEVEL_CONTROLLER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <husky_highlevel_controller/AddTwoIntsRequest.h>
#include <husky_highlevel_controller/AddTwoIntsResponse.h>


namespace husky_highlevel_controller
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace husky_highlevel_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_highlevel_controller::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::husky_highlevel_controller::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::husky_highlevel_controller::AddTwoInts > {
  static const char* value()
  {
    return "husky_highlevel_controller/AddTwoInts";
  }

  static const char* value(const ::husky_highlevel_controller::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::husky_highlevel_controller::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::husky_highlevel_controller::AddTwoInts >
template<>
struct MD5Sum< ::husky_highlevel_controller::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_highlevel_controller::AddTwoInts >::value();
  }
  static const char* value(const ::husky_highlevel_controller::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_highlevel_controller::AddTwoIntsRequest> should match
// service_traits::DataType< ::husky_highlevel_controller::AddTwoInts >
template<>
struct DataType< ::husky_highlevel_controller::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::husky_highlevel_controller::AddTwoInts >::value();
  }
  static const char* value(const ::husky_highlevel_controller::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_highlevel_controller::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::husky_highlevel_controller::AddTwoInts >
template<>
struct MD5Sum< ::husky_highlevel_controller::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_highlevel_controller::AddTwoInts >::value();
  }
  static const char* value(const ::husky_highlevel_controller::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_highlevel_controller::AddTwoIntsResponse> should match
// service_traits::DataType< ::husky_highlevel_controller::AddTwoInts >
template<>
struct DataType< ::husky_highlevel_controller::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::husky_highlevel_controller::AddTwoInts >::value();
  }
  static const char* value(const ::husky_highlevel_controller::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_HIGHLEVEL_CONTROLLER_MESSAGE_ADDTWOINTS_H
