// Generated by gencpp from file husky_highlevel_controller/MulTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef HUSKY_HIGHLEVEL_CONTROLLER_MESSAGE_MULTWOINTSRESPONSE_H
#define HUSKY_HIGHLEVEL_CONTROLLER_MESSAGE_MULTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_highlevel_controller
{
template <class ContainerAllocator>
struct MulTwoIntsResponse_
{
  typedef MulTwoIntsResponse_<ContainerAllocator> Type;

  MulTwoIntsResponse_()
    : m(0)  {
    }
  MulTwoIntsResponse_(const ContainerAllocator& _alloc)
    : m(0)  {
  (void)_alloc;
    }



   typedef int64_t _m_type;
  _m_type m;





  typedef boost::shared_ptr< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MulTwoIntsResponse_

typedef ::husky_highlevel_controller::MulTwoIntsResponse_<std::allocator<void> > MulTwoIntsResponse;

typedef boost::shared_ptr< ::husky_highlevel_controller::MulTwoIntsResponse > MulTwoIntsResponsePtr;
typedef boost::shared_ptr< ::husky_highlevel_controller::MulTwoIntsResponse const> MulTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator1> & lhs, const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.m == rhs.m;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator1> & lhs, const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_highlevel_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ac4ba103c999804b94081b0534fca93";
  }

  static const char* value(const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ac4ba103c999804ULL;
  static const uint64_t static_value2 = 0xb94081b0534fca93ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_highlevel_controller/MulTwoIntsResponse";
  }

  static const char* value(const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 m\n"
;
  }

  static const char* value(const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MulTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_highlevel_controller::MulTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "m: ";
    Printer<int64_t>::stream(s, indent + "  ", v.m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_HIGHLEVEL_CONTROLLER_MESSAGE_MULTWOINTSRESPONSE_H
