(cl:defpackage husky_highlevel_controller-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "MULTWOINTS"
   "<MULTWOINTS-REQUEST>"
   "MULTWOINTS-REQUEST"
   "<MULTWOINTS-RESPONSE>"
   "MULTWOINTS-RESPONSE"
   "RADIANTOANGLE"
   "<RADIANTOANGLE-REQUEST>"
   "RADIANTOANGLE-REQUEST"
   "<RADIANTOANGLE-RESPONSE>"
   "RADIANTOANGLE-RESPONSE"
  ))

